### ISSUE TITLE
可不可用对日期 时间 可变数据设置自定义样式

### ISSUE THREAD

**Issue by lhj5426** [utags/utags#11]
![image](https://github.com/utags/utags/assets/30548000/a8565cc0-0764-4fa0-a34d-be739dc45cca)
如图 大佬 这种 
2023年09月18日，11点41分49秒，扫揽分割线
这种年月日的时间  2023年09月18日 是每天在变化的
现在的样式 可用 给某一个标签 改变特定样式 或者全局修改样式 
但是这种日期的可变内容 有没有办法可用设置一个 独特的样式 ？
无论怎么变化 2023年09月18日 2023年10月01日 2077年17月77日
这样的格式 无论时间数字怎么变化 对这个格式设置的单独样式均可生效的
还有时间格式 11点48分19秒 也是

**Comment by lhj5426** [comment]
> @lhj5426 虽然不理解为什么要添加内容为日期和时间的标签， 如果要给这种类型的标签自定义样式，可以试试
> 
> ```css
> /* 2023 开头的标签 */
> :not(#a):not(#a):not(#a) .utags_text_tag[data-utags_tag^="2023"] {
>     color: white !important;
>     border: 1px solid red !important;
>     background-color: red !important;
> }
> ```
> 
> ```css
> /* 同时包含 '年' '月' '日' 的标签 */
> :not(#a):not(#a):not(#a) .utags_text_tag[data-utags_tag*="年"][data-utags_tag*="月"][data-utags_tag*="日"]   {
>     color: white !important;
>     border: 1px solid red !important;
>     background-color: red !important;
> }
> 
> /* 同时包含 '点' '分' '秒' 的标签 */
> :not(#a):not(#a):not(#a) .utags_text_tag[data-utags_tag*="点"][data-utags_tag*="分"][data-utags_tag*="秒"]   {
>     color: white !important;
>     border: 1px solid red !important;
>     background-color: red !important;
> }
> ```

真的非常感谢大佬 

添加时间日期 属于强迫症的一种吧
我喜欢逛某网站 而某网站更新速度很快
这样有个标签做分割线 
我可以知道上次我具体浏览到哪了
 该从哪浏览了
标签嘛不一定是标签 有可能是 【标记】
![image](https://github.com/utags/utags/assets/30548000/596c5e05-0bf5-411b-af27-aae1ae0f1b05)
![image](https://github.com/utags/utags/assets/30548000/092558a5-f014-4312-bc31-1074e96354ea)
刚刚试过 非常 的棒

**Comment by PipecraftNet** [comment]
0.9.0 版本以后，像上面日期、时间格式的标签的颜色，可以简化为下面的写法。

```css
/* 2023 开头的标签 */
.utags_text_tag[data-utags_tag^="2023"] {
    --utags-text-tag-color: white;
    --utags-text-tag-border-color: red;
    --utags-text-tag-background-color: red;
}

/* 同时包含 '年' '月' '日' 的标签 */
.utags_text_tag[data-utags_tag*="点"][data-utags_tag*="分"][data-utags_tag*="秒"] {
    --utags-text-tag-color: white;
    --utags-text-tag-border-color: red;
    --utags-text-tag-background-color: red;
}

/* 同时包含 '年' '月' '日' 的标签 */
.utags_text_tag[data-utags_tag*="年"][data-utags_tag*="月"][data-utags_tag*="日"] {
    --utags-text-tag-color: white;
    --utags-text-tag-border-color: green;
    --utags-text-tag-background-color: green;
}
```
