### ISSUE TITLE
请问可以支持下这个网站吗 

### ISSUE THREAD

**Issue by lhj5426** [utags/utags#12]
https://myanimelist.net/
主要是 这个页面 https://myanimelist.net/animelist/
追番页面 

![image](https://github.com/utags/utags/assets/30548000/0833dfad-671f-45e3-85e5-7d5dc579e9b9)

如果可以用标签 标注 中文名 就方便很多了

**Comment by PipecraftNet** [comment]
> https://myanimelist.net/
目前在做一个功能更新，等完成这个功能了，再适配这个网站并通知你吧。

> 主要是 这个页面 https://myanimelist.net/animelist/
这个页面显示 404，是需要登录才能看到吗？

**Comment by lhj5426** [comment]
> > https://myanimelist.net/
> 
> 目前在做一个功能更新，等完成这个功能了，再适配这个网站并通知你吧。
> 
> > 主要是 这个页面 https://myanimelist.net/animelist/
> 
> 这个页面显示 404，是需要登录才能看到吗？

 嗯 这个网址 需要登录才能看到 
 实际上 是这个样子的
 https://myanimelist.net/animelist/lhj5426
 斜杠后边是用户名 这样就不404了

**Comment by PipecraftNet** [comment]
@lhj5426 

已对此网站进行适配，请看看还有哪些地方需要改善，欢迎留言反馈。

![2023-10-24-13-55-55](https://github.com/utags/utags/assets/88728670/1cc8b370-da05-45a8-8962-c65d2b57d81a)

----

![2023-10-24-14-07-01](https://github.com/utags/utags/assets/88728670/6f198274-dd70-47fc-a72c-1a19ada6217c)

**Comment by PipecraftNet** [comment]
@lhj5426 

还真没注意到小雷达图标。下个版本修复这个问题。

另外，从 0.9.0 版本开始，修改标签样式可以简化为下面这样，与上面的代码效果相同。参考 https://discuss-cn.bestxtools.com/d/699

```css
a {
  --utags-text-tag-color: white;
  --utags-text-tag-border-color: red;
  --utags-text-tag-background-color: red;
}
```

改变字体大小会麻烦些，元素的高度也要修改。先用下面的代码试一下。下个版本优化代码，方便修改高度。
```css
:not(#a):not(#a):not(#a) .utags_text_tag[data-utags_tag] {
    height: unset !important;
}

:not(#a):not(#a):not(#a) .utags_text_tag[data-utags_tag]::before {
    font-size: 24px;
    height: unset;
}
```

**Comment by lhj5426** [comment]
> @lhj5426*
> 
> 还真没注意到小雷达图标。下个版本修复这个问题。
> 
> 另外，从 0.9.0 版本开始，修改标签样式可以简化为下面这样，与上面的代码效果相同。参考 https://discuss-cn.bestxtools.com/d/699*
> 
> ```css
> a {
>   --utags-text-tag-color: white;
>   --utags-text-tag-border-color: red;
>   --utags-text-tag-background-color: red;
> }
> ```
> 
> 改变字体大小会麻烦些，元素的高度也要修改。先用下面的代码试一下。下个版本优化代码，方便修改高度。
> 
> ```css
> :not(#a):not(#a):not(#a) .utags_text_tag[data-utags_tag] {
>     height: unset !important;
> }
> 
> :not(#a):not(#a):not(#a) .utags_text_tag[data-utags_tag]::before {
>     font-size: 24px;
>     height: unset;
> }
> ```

![image](https://github.com/utags/utags/assets/30548000/0fa0e9e5-8c66-4f13-b493-fb23f85e6f92)
这样 好了很多 感谢

**Comment by PipecraftNet** [comment]
@lhj5426 刚刚发布了 0.9.4 版本，
- 修复了小鱼标签图标与小雷达图标重叠的问题
- 优化了修改字体大小的方式，参考下面代码
```css
body {
    /* 标签文字字体大小 */
    --utags-text-tag-font-size: 15px;
}
```

更多自定义样式（颜色，字体）方法参考 https://discuss-cn.bestxtools.com/d/699
