### ISSUE TITLE
文字显示不全

### ISSUE THREAD

**Issue by lhj5426** [utags/utags#26]
![Image](https://github.com/user-attachments/assets/fde7d28c-fc16-4de2-898e-d811ae94d34f)

![Image](https://github.com/user-attachments/assets/bf305122-3c54-42bd-9df7-0c71de28ff3a) 

如图所示 标签文字显示不全
以前是可以显示全部的

是新版修改了样式吗？
我还是用的去年 原来的 CSS
/*小鱼标签样式*/

/*全局默认标签样式修改*/
body {
  --utags-text-tag-color: white;
  --utags-text-tag-border-color: red;
  --utags-text-tag-background-color: red;
}

/*自定义标签样式*/
/* 同时包含 '年' '月' '日' 的标签 */
.utags_text_tag[data-utags_tag*="年"][data-utags_tag*="月"][data-utags_tag*="日"] {
    --utags-text-tag-color: rgb(199, 14, 14);
    --utags-text-tag-border-color: rgb(15, 245, 7);
    --utags-text-tag-background-color: rgb(208, 255, 0);
          /* 标签文字字体大小 */
  --utags-text-tag-font-size: 16px;
}

/* 同时包含 '点' '分' '秒' 的标签 */
.utags_text_tag[data-utags_tag*="点"][data-utags_tag*="分"][data-utags_tag*="秒"] {
    --utags-text-tag-color: rgb(243, 235, 235);
    --utags-text-tag-border-color: rgb(68, 0, 255);
    --utags-text-tag-background-color: rgb(255, 0, 242);
          /* 标签文字字体大小 */
  --utags-text-tag-font-size: 16px;
}

**Comment by lhj5426** [comment]
![Image](https://github.com/user-attachments/assets/adbb7f73-bd09-42fc-8694-cdaae665a2ca) 之前这几个字都是可以显示全的 现在都被省略号了

**Comment by lhj5426** [comment]
前段时间 

![Image](https://github.com/user-attachments/assets/8809fd5e-11f4-4363-8ff9-ec5806a778e2)显示这么多字都可以现在
现最最多显示 6个字

![Image](https://github.com/user-attachments/assets/0db3cde9-ca3d-4a6d-8131-8919be2837bd)  
一二三四五六七八九十 就显示到6

**Comment by PipecraftNet** [comment]
因为标签很长时，在很多网站上显示会很乱。
所以前几天改成了显示时限制最大长度，鼠标移到上面时，tooltip 会显示全部。

如果想在特定网站上显示标签的全部内容，添加自定义样式可以解决。

```css
  /* 标签最大宽度 */
  --utags-text-tag-max-width: 100%; /* 默认 90px */
```

**Comment by PipecraftNet** [comment]
试一下，如果还有问题请告诉我。

**Comment by PipecraftNet** [comment]
[0.12.6 版本](https://greasyfork.org/zh-CN/scripts/460718-utags-add-usertags-to-links)添加了 `--utags-text-tag-white-space` 自定义样式变量，控制是否换行显示。`nowrap` 不换行，`normal` 换行。

结合上面的 `--utags-text-tag-max-width` 一起使用的例子:

```css
/* 所有标签显示全部内容，换行 */
body {
  /* 标签最大宽度 */
  --utags-text-tag-max-width: 100%; /* 默认 90px */
  --utags-text-tag-white-space: normal;
}
```

```css
/* 同时包含 '年' '月' '日' 的标签 /
/* 显示全部内容，不换行 */
.utags_text_tag[data-utags_tag*="年"][data-utags_tag*="月"][data-utags_tag*="日"] {
  --utags-text-tag-color: rgb(199, 14, 14);
  --utags-text-tag-border-color: rgb(15, 245, 7);
  --utags-text-tag-background-color: rgb(208, 255, 0);
  /* 标签文字字体大小 */
  --utags-text-tag-font-size: 16px;
  /* 标签最大宽度 */
  --utags-text-tag-max-width: 100%; /* 默认 90px */
  --utags-text-tag-white-space: nowrap;
}

```
